<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Category;
use App\Models\House;
use App\Models\ClassSection;

class OnlineAdmissionSeeder extends Seeder
{
    public function run(): void
    {
        if (DB::table('online_admissions')->exists()) {
            return;
        }

        $classSection = ClassSection::first();
        if (!$classSection) {
            return;
        }

        $categoryIds = Category::pluck('id')->toArray();
        $houseIds = House::pluck('id')->toArray();

        $vehicleId = DB::table('vehicles')->insertGetId([
            'vehicle_no' => 'ABC 1234',
            'vehicle_model' => 'Toyota Hiace',
            'manufacture_year' => '2023',
            'registration_number' => 'REG-001',
            'chasis_number' => 'CHS-001',
            'max_seating_capacity' => '15',
            'driver_name' => 'محمد السالم',
            'driver_licence' => 'LIC-001',
            'driver_contact' => '0555777700',
            'note' => '',
            'created_at' => now(),
        ]);

        $route = DB::table('transport_route')->first();
        if (!$route) {
            return;
        }

        $vehrouteId = DB::table('vehicle_routes')->insertGetId([
            'route_id' => $route->id,
            'vehicle_id' => $vehicleId,
            'created_at' => now(),
        ]);

        $hostelRoom = DB::table('hostel_rooms')->first();

        $onlineAdmissions = [
            [
                'reference_no' => 'ONL-2025-001',
                'firstname' => 'أحمد',
                'middlename' => 'خالد',
                'lastname' => 'الناصر',
                'admission_no' => 'ONLADM25001',
                'roll_no' => '201',
                'admission_date' => '2025-09-01',
                'class_section_id' => $classSection->id,
                'category_id' => $categoryIds[array_rand($categoryIds)] ?? null,
                'school_house_id' => $houseIds[array_rand($houseIds)] ?? null,
                'dob' => '2012-03-15',
                'gender' => 'Male',
                'mobileno' => '0555111101',
                'email' => 'ahmed.almasser@email.com',
                'state' => 'الرياض',
                'city' => 'الرياض',
                'pincode' => '12345',
                'religion' => 'الإسلام',
                'cast' => '',
                'current_address' => 'حي النزهة، الرياض',
                'permanent_address' => 'حي النزهة، الرياض',
                'father_name' => 'خالد الناصر',
                'father_phone' => '0555111100',
                'father_occupation' => 'مهندس',
                'mother_name' => 'نورة الناصر',
                'mother_phone' => '0555111102',
                'mother_occupation' => 'ربة منزل',
                'guardian_is' => 'father',
                'guardian_name' => 'خالد الناصر',
                'guardian_relation' => 'والد',
                'guardian_phone' => '0555111100',
                'guardian_email' => 'khalid.almasser@email.com',
                'guardian_occupation' => 'مهندس',
                'guardian_address' => 'حي النزهة، الرياض',
                'blood_group' => 'A+',
                'vehroute_id' => $vehrouteId,
                'route_id' => $route->id,
                'hostel_room_id' => $hostelRoom?->id,
                'form_status' => 1,
                'paid_status' => 1,
                'is_enroll' => 1,
                'submit_date' => '2025-08-20',
                'document' => '',
                'image' => '',
                'father_pic' => '',
                'mother_pic' => '',
                'guardian_pic' => '',
                'previous_school' => 'مدارس الرياض الأهلية',
                'height' => '145',
                'weight' => '38',
                'measurement_date' => '2025-09-01',
                'note' => 'طالب مجتهد',
                'rte' => 'No',
                'adhar_no' => '1234-5678-9012',
                'samagra_id' => '',
                'bank_account_no' => '',
                'bank_name' => '',
                'ifsc_code' => '',
                'created_at' => '2025-08-20 10:30:00',
            ],
            [
                'reference_no' => 'ONL-2025-002',
                'firstname' => 'سارة',
                'middlename' => 'عبدالله',
                'lastname' => 'القحطاني',
                'admission_no' => null,
                'roll_no' => null,
                'admission_date' => null,
                'class_section_id' => $classSection->id,
                'category_id' => $categoryIds[array_rand($categoryIds)] ?? null,
                'school_house_id' => $houseIds[array_rand($houseIds)] ?? null,
                'dob' => '2013-07-22',
                'gender' => 'Female',
                'mobileno' => '0555222201',
                'email' => 'sara.alqahtani@email.com',
                'state' => 'الرياض',
                'city' => 'الرياض',
                'pincode' => '12345',
                'religion' => 'الإسلام',
                'cast' => '',
                'current_address' => 'حي العليا، الرياض',
                'permanent_address' => 'حي العليا، الرياض',
                'father_name' => 'عبدالله القحطاني',
                'father_phone' => '0555222200',
                'father_occupation' => 'طبيب',
                'mother_name' => 'هند القحطاني',
                'mother_phone' => '0555222202',
                'mother_occupation' => 'معلمة',
                'guardian_is' => 'father',
                'guardian_name' => 'عبدالله القحطاني',
                'guardian_relation' => 'والد',
                'guardian_phone' => '0555222200',
                'guardian_email' => 'abdullah.alqahtani@email.com',
                'guardian_occupation' => 'طبيب',
                'guardian_address' => 'حي العليا، الرياض',
                'blood_group' => 'B+',
                'vehroute_id' => $vehrouteId,
                'route_id' => $route->id,
                'hostel_room_id' => null,
                'form_status' => 1,
                'paid_status' => 1,
                'is_enroll' => 0,
                'submit_date' => '2025-09-05',
                'document' => '',
                'image' => '',
                'father_pic' => '',
                'mother_pic' => '',
                'guardian_pic' => '',
                'previous_school' => '',
                'height' => '',
                'weight' => '',
                'measurement_date' => null,
                'note' => '',
                'rte' => 'No',
                'adhar_no' => '',
                'samagra_id' => '',
                'bank_account_no' => '',
                'bank_name' => '',
                'ifsc_code' => '',
                'created_at' => '2025-09-05 14:20:00',
            ],
            [
                'reference_no' => 'ONL-2025-003',
                'firstname' => 'عمر',
                'middlename' => 'سعيد',
                'lastname' => 'الزهراني',
                'admission_no' => null,
                'roll_no' => null,
                'admission_date' => null,
                'class_section_id' => $classSection->id,
                'category_id' => $categoryIds[array_rand($categoryIds)] ?? null,
                'school_house_id' => $houseIds[array_rand($houseIds)] ?? null,
                'dob' => '2012-11-08',
                'gender' => 'Male',
                'mobileno' => '0555333301',
                'email' => 'omar.alzahrani@email.com',
                'state' => 'مكة المكرمة',
                'city' => 'جدة',
                'pincode' => '23456',
                'religion' => 'الإسلام',
                'cast' => '',
                'current_address' => 'حي الشاطئ، جدة',
                'permanent_address' => 'حي الشاطئ، جدة',
                'father_name' => 'سعيد الزهراني',
                'father_phone' => '0555333300',
                'father_occupation' => 'تاجر',
                'mother_name' => 'مريم الزهراني',
                'mother_phone' => '0555333302',
                'mother_occupation' => 'ربة منزل',
                'guardian_is' => 'father',
                'guardian_name' => 'سعيد الزهراني',
                'guardian_relation' => 'والد',
                'guardian_phone' => '0555333300',
                'guardian_email' => 'saeed.alzahrani@email.com',
                'guardian_occupation' => 'تاجر',
                'guardian_address' => 'حي الشاطئ، جدة',
                'blood_group' => 'O+',
                'vehroute_id' => 0,
                'route_id' => 0,
                'hostel_room_id' => null,
                'form_status' => 0,
                'paid_status' => 0,
                'is_enroll' => 0,
                'submit_date' => null,
                'document' => '',
                'image' => '',
                'father_pic' => '',
                'mother_pic' => '',
                'guardian_pic' => '',
                'previous_school' => '',
                'height' => '',
                'weight' => '',
                'measurement_date' => null,
                'note' => '',
                'rte' => 'No',
                'adhar_no' => '',
                'samagra_id' => '',
                'bank_account_no' => '',
                'bank_name' => '',
                'ifsc_code' => '',
                'created_at' => '2025-09-10 09:15:00',
            ],
            [
                'reference_no' => 'ONL-2025-004',
                'firstname' => 'ليلى',
                'middlename' => 'محمد',
                'lastname' => 'العتيبي',
                'admission_no' => 'ONLADM25004',
                'roll_no' => '202',
                'admission_date' => '2025-09-15',
                'class_section_id' => $classSection->id,
                'category_id' => $categoryIds[array_rand($categoryIds)] ?? null,
                'school_house_id' => $houseIds[array_rand($houseIds)] ?? null,
                'dob' => '2013-02-14',
                'gender' => 'Female',
                'mobileno' => '0555444401',
                'email' => 'layla.alotaibi@email.com',
                'state' => 'الرياض',
                'city' => 'الرياض',
                'pincode' => '12345',
                'religion' => 'الإسلام',
                'cast' => '',
                'current_address' => 'حي السعادة، الرياض',
                'permanent_address' => 'حي السعادة، الرياض',
                'father_name' => 'محمد العتيبي',
                'father_phone' => '0555444400',
                'father_occupation' => 'محاسب',
                'mother_name' => 'فاطمة العتيبي',
                'mother_phone' => '0555444402',
                'mother_occupation' => 'ربة منزل',
                'guardian_is' => 'father',
                'guardian_name' => 'محمد العتيبي',
                'guardian_relation' => 'والد',
                'guardian_phone' => '0555444400',
                'guardian_email' => 'mohammed.alotaibi@email.com',
                'guardian_occupation' => 'محاسب',
                'guardian_address' => 'حي السعادة، الرياض',
                'blood_group' => 'AB+',
                'vehroute_id' => 0,
                'route_id' => 0,
                'hostel_room_id' => null,
                'form_status' => 1,
                'paid_status' => 2,
                'is_enroll' => 0,
                'submit_date' => '2025-09-12',
                'document' => '',
                'image' => '',
                'father_pic' => '',
                'mother_pic' => '',
                'guardian_pic' => '',
                'previous_school' => 'مدارس الأندلس',
                'height' => '',
                'weight' => '',
                'measurement_date' => null,
                'note' => 'قيد المعالجة',
                'rte' => 'Yes',
                'adhar_no' => '',
                'samagra_id' => '',
                'bank_account_no' => '',
                'bank_name' => '',
                'ifsc_code' => '',
                'created_at' => '2025-09-12 11:45:00',
            ],
            [
                'reference_no' => 'ONL-2025-005',
                'firstname' => 'فيصل',
                'middlename' => 'نايف',
                'lastname' => 'الدوسري',
                'admission_no' => 'ONLADM25005',
                'roll_no' => '203',
                'admission_date' => '2025-09-20',
                'class_section_id' => $classSection->id,
                'category_id' => $categoryIds[array_rand($categoryIds)] ?? null,
                'school_house_id' => $houseIds[array_rand($houseIds)] ?? null,
                'dob' => '2012-06-30',
                'gender' => 'Male',
                'mobileno' => '0555555501',
                'email' => 'faisal.aldosari@email.com',
                'state' => 'الرياض',
                'city' => 'الرياض',
                'pincode' => '12345',
                'religion' => 'الإسلام',
                'cast' => '',
                'current_address' => 'حي الربيع، الرياض',
                'permanent_address' => 'حي الربيع، الرياض',
                'father_name' => 'نايف الدوسري',
                'father_phone' => '0555555500',
                'father_occupation' => 'عسكري',
                'mother_name' => 'حصة الدوسري',
                'mother_phone' => '0555555502',
                'mother_occupation' => 'ربة منزل',
                'guardian_is' => 'father',
                'guardian_name' => 'نايف الدوسري',
                'guardian_relation' => 'والد',
                'guardian_phone' => '0555555500',
                'guardian_email' => 'naif.aldosari@email.com',
                'guardian_occupation' => 'عسكري',
                'guardian_address' => 'حي الربيع، الرياض',
                'blood_group' => 'A-',
                'vehroute_id' => $vehrouteId,
                'route_id' => $route->id,
                'hostel_room_id' => $hostelRoom?->id,
                'form_status' => 1,
                'paid_status' => 1,
                'is_enroll' => 1,
                'submit_date' => '2025-09-15',
                'document' => '',
                'image' => '',
                'father_pic' => '',
                'mother_pic' => '',
                'guardian_pic' => '',
                'previous_school' => 'مدارس الفلاح',
                'height' => '150',
                'weight' => '42',
                'measurement_date' => '2025-09-20',
                'note' => '',
                'rte' => 'No',
                'adhar_no' => '9876-5432-1098',
                'samagra_id' => '',
                'bank_account_no' => '',
                'bank_name' => '',
                'ifsc_code' => '',
                'created_at' => '2025-09-15 08:00:00',
            ],
            [
                'reference_no' => 'ONL-2025-006',
                'firstname' => 'نورة',
                'middlename' => 'حسن',
                'lastname' => 'الشهري',
                'admission_no' => null,
                'roll_no' => null,
                'admission_date' => null,
                'class_section_id' => $classSection->id,
                'category_id' => $categoryIds[array_rand($categoryIds)] ?? null,
                'school_house_id' => $houseIds[array_rand($houseIds)] ?? null,
                'dob' => '2013-09-05',
                'gender' => 'Female',
                'mobileno' => '0555666601',
                'email' => 'noura.alshehri@email.com',
                'state' => 'الرياض',
                'city' => 'الرياض',
                'pincode' => '12345',
                'religion' => 'الإسلام',
                'cast' => '',
                'current_address' => 'حي الملقا، الرياض',
                'permanent_address' => 'حي الملقا، الرياض',
                'father_name' => 'حسن الشهري',
                'father_phone' => '0555666600',
                'father_occupation' => 'مدير شركة',
                'mother_name' => 'عائشة الشهري',
                'mother_phone' => '0555666602',
                'mother_occupation' => 'مهندسة',
                'guardian_is' => 'father',
                'guardian_name' => 'حسن الشهري',
                'guardian_relation' => 'والد',
                'guardian_phone' => '0555666600',
                'guardian_email' => 'hassan.alshehri@email.com',
                'guardian_occupation' => 'مدير شركة',
                'guardian_address' => 'حي الملقا، الرياض',
                'blood_group' => 'O-',
                'vehroute_id' => 0,
                'route_id' => 0,
                'hostel_room_id' => null,
                'form_status' => 1,
                'paid_status' => 0,
                'is_enroll' => 0,
                'submit_date' => '2025-09-18',
                'document' => '',
                'image' => '',
                'father_pic' => '',
                'mother_pic' => '',
                'guardian_pic' => '',
                'previous_school' => '',
                'height' => '',
                'weight' => '',
                'measurement_date' => null,
                'note' => 'بانتظار تأكيد الدفع',
                'rte' => 'No',
                'adhar_no' => '',
                'samagra_id' => '',
                'bank_account_no' => '',
                'bank_name' => '',
                'ifsc_code' => '',
                'created_at' => '2025-09-18 16:30:00',
            ],
        ];

        foreach ($onlineAdmissions as $data) {
            $data['updated_at'] = now();
            $id = DB::table('online_admissions')->insertGetId($data);

            if (($data['paid_status'] ?? 0) == 1) {
                DB::table('online_admission_payment')->insert([
                    'online_admission_id' => $id,
                    'paid_amount' => 500.00,
                    'payment_mode' => 'online',
                    'payment_type' => 'full',
                    'transaction_id' => 'TXN-' . str_pad($id, 6, '0', STR_PAD_LEFT),
                    'note' => 'تم الدفع بنجاح',
                    'date' => $data['created_at'],
                ]);
            }

            if (($data['paid_status'] ?? 0) == 2) {
                DB::table('online_admission_payment')->insert([
                    'online_admission_id' => $id,
                    'paid_amount' => 250.00,
                    'payment_mode' => 'online',
                    'payment_type' => 'partial',
                    'transaction_id' => 'TXN-' . str_pad($id, 6, '0', STR_PAD_LEFT),
                    'note' => 'دفعة أولى',
                    'date' => $data['created_at'],
                ]);
            }
        }

        if (!DB::table('online_admission_fields')->exists()) {
            $fields = [
                ['name' => 'firstname', 'status' => 1],
                ['name' => 'lastname', 'status' => 1],
                ['name' => 'class_section_id', 'status' => 1],
                ['name' => 'dob', 'status' => 1],
                ['name' => 'gender', 'status' => 1],
                ['name' => 'category_id', 'status' => 1],
                ['name' => 'mobileno', 'status' => 1],
                ['name' => 'email', 'status' => 1],
                ['name' => 'father_name', 'status' => 1],
                ['name' => 'father_phone', 'status' => 1],
                ['name' => 'mother_name', 'status' => 1],
                ['name' => 'mother_phone', 'status' => 1],
                ['name' => 'guardian_name', 'status' => 1],
                ['name' => 'guardian_relation', 'status' => 1],
                ['name' => 'guardian_phone', 'status' => 1],
                ['name' => 'guardian_email', 'status' => 1],
            ];
            foreach ($fields as $field) {
                DB::table('online_admission_fields')->insert($field);
            }
        }
    }
}
