<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SettingSeeder extends Seeder
{
    public function run(): void
    {
        if (DB::table('sch_settings')->exists()) {
            return;
        }

        DB::table('sch_settings')->insert([
            'id' => 1,
            'name' => 'Smart School',
            'email' => 'admin@smartschool.com',
            'phone' => '0555000000',
            'address' => 'الرياض، المملكة العربية السعودية',
            'base_url' => 'http://localhost:8000',
            'folder_path' => '',
            'biometric' => 0,
            'biometric_device' => '',
            'lang_id' => 4,
            'languages' => 'english,arabic',
            'dise_code' => '',
            'date_format' => 'd/m/Y',
            'time_format' => 'h:i A',
            'currency' => 124,
            'currency_symbol' => 'ر.س',
            'currency_place' => 'before_number',
            'currency_format' => '#,###.##',
            'is_rtl' => 'enabled',
            'is_duplicate_fees_invoice' => 0,
            'collect_back_date_fees' => 0,
            'single_page_print' => 0,
            'timezone' => 'Asia/Riyadh',
            'session_id' => null,
            'cron_secret_key' => 'smart_school_cron_key',
            'class_teacher' => '1',
            'start_month' => '1',
            'attendence_type' => 0,
            'low_attendance_limit' => 75,
            'image' => '',
            'admin_logo' => '',
            'admin_small_logo' => '',
            'admin_login_page_background' => '',
            'user_login_page_background' => '',
            'theme' => 'default.jpg',
            'fee_due_days' => 0,
            'adm_auto_insert' => 1,
            'adm_prefix' => 'ADM',
            'adm_start_from' => '1',
            'adm_no_digit' => 6,
            'adm_update_status' => 0,
            'staffid_auto_insert' => 1,
            'staffid_prefix' => 'STF',
            'staffid_start_from' => '1',
            'staffid_no_digit' => 6,
            'staffid_update_status' => 0,
            'is_active' => 'yes',
            'online_admission' => 0,
            'online_admission_payment' => 'none',
            'online_admission_amount' => 0,
            'online_admission_instruction' => '',
            'online_admission_conditions' => '',
            'online_admission_application_form' => '',
            'exam_result' => 1,
            'is_blood_group' => 1,
            'is_student_house' => 1,
            'roll_no' => 1,
            'category' => 1,
            'religion' => 1,
            'cast' => 1,
            'mobile_no' => 1,
            'student_email' => 1,
            'admission_date' => 1,
            'lastname' => 1,
            'middlename' => 1,
            'student_photo' => 1,
            'student_height' => 1,
            'student_weight' => 1,
            'measurement_date' => 1,
            'father_name' => 1,
            'father_phone' => 1,
            'father_occupation' => 1,
            'father_pic' => 1,
            'mother_name' => 1,
            'mother_phone' => 1,
            'mother_occupation' => 1,
            'mother_pic' => 1,
            'guardian_name' => 1,
            'guardian_relation' => 1,
            'guardian_phone' => 1,
            'guardian_email' => 1,
            'guardian_pic' => 1,
            'guardian_occupation' => 1,
            'guardian_address' => 1,
            'current_address' => 1,
            'permanent_address' => 1,
            'route_list' => 1,
            'hostel_id' => 1,
            'bank_account_no' => 1,
            'ifsc_code' => 1,
            'bank_name' => 1,
            'national_identification_no' => 1,
            'local_identification_no' => 1,
            'rte' => 1,
            'previous_school_details' => 1,
            'student_note' => 1,
            'upload_documents' => 1,
            'student_barcode' => 1,
            'staff_designation' => 1,
            'staff_department' => 1,
            'staff_last_name' => 1,
            'staff_father_name' => 1,
            'staff_mother_name' => 1,
            'staff_date_of_joining' => 1,
            'staff_phone' => 1,
            'staff_emergency_contact' => 1,
            'staff_marital_status' => 1,
            'staff_photo' => 1,
            'staff_current_address' => 1,
            'staff_permanent_address' => 1,
            'staff_qualification' => 1,
            'staff_work_experience' => 1,
            'staff_note' => 1,
            'staff_epf_no' => 1,
            'staff_basic_salary' => 1,
            'staff_contract_type' => 1,
            'staff_work_shift' => 1,
            'staff_work_location' => 1,
            'staff_leaves' => 1,
            'staff_account_details' => 1,
            'staff_social_media' => 1,
            'staff_upload_documents' => 1,
            'staff_barcode' => 1,
            'staff_notification_email' => 'staff@smartschool.com',
            'mobile_api_url' => '',
            'admin_mobile_api_url' => '',
            'app_primary_color_code' => '#435EE6',
            'app_secondary_color_code' => '#37B24D',
            'admin_app_primary_color_code' => '#435EE6',
            'admin_app_secondary_color_code' => '#37B24D',
            'app_logo' => '',
            'student_profile_edit' => 0,
            'start_week' => 'monday',
            'my_question' => 1,
            'superadmin_restriction' => 'no',
            'student_timeline' => 'yes',
            'calendar_event_reminder' => 0,
            'event_reminder' => 'yes',
            'student_login' => '',
            'parent_login' => '',
            'student_panel_login' => 1,
            'parent_panel_login' => 1,
            'is_student_feature_lock' => 0,
            'maintenance_mode' => 0,
            'lock_grace_period' => 0,
            'is_offline_fee_payment' => 0,
            'offline_bank_payment_instruction' => '',
            'scan_code_type' => 'barcode',
        ]);
    }
}
