<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('sch_settings', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('base_url', 500)->nullable();
            $table->text('folder_path')->nullable();
            $table->string('name', 100)->nullable();
            $table->integer('biometric')->nullable()->default(0);
            $table->text('biometric_device')->nullable();
            $table->string('email', 100)->nullable();
            $table->string('phone', 50)->nullable();
            $table->text('address')->nullable();
            $table->integer('lang_id')->nullable();
            $table->string('languages', 500);
            $table->string('dise_code', 50)->nullable();
            $table->string('date_format', 50);
            $table->string('time_format', 255);
            $table->string('currency', 50);
            $table->string('currency_symbol', 50);
            $table->string('is_rtl', 10)->nullable()->default('disabled');
            $table->string('is_duplicate_fees_invoice', 100)->nullable()->default(0);
            $table->integer('collect_back_date_fees');
            $table->integer('single_page_print')->nullable()->default(0);
            $table->string('timezone', 30)->nullable()->default('UTC');
            $table->integer('session_id')->nullable();
            $table->string('cron_secret_key', 100);
            $table->string('currency_place', 50)->default('before_number');
            $table->string('currency_format', 20)->nullable();
            $table->string('class_teacher', 100);
            $table->string('start_month', 40);
            $table->integer('attendence_type')->default(0);
            $table->float('low_attendance_limit', 10, 2);
            $table->string('image', 100)->nullable();
            $table->string('admin_logo', 255);
            $table->string('admin_small_logo', 255);
            $table->string('admin_login_page_background', 255);
            $table->string('user_login_page_background', 255);
            $table->string('theme', 200)->default('default.jpg');
            $table->integer('fee_due_days')->nullable()->default(0);
            $table->integer('adm_auto_insert')->default(1);
            $table->string('adm_prefix', 50)->default('ssadm19/20');
            $table->string('adm_start_from', 11);
            $table->integer('adm_no_digit')->default(6);
            $table->integer('adm_update_status')->default(0);
            $table->integer('staffid_auto_insert')->default(1);
            $table->string('staffid_prefix', 100)->default('staffss/19/20');
            $table->string('staffid_start_from', 50);
            $table->integer('staffid_no_digit')->default(6);
            $table->integer('staffid_update_status')->default(0);
            $table->string('is_active', 255)->nullable()->default('no');
            $table->integer('online_admission')->nullable()->default(0);
            $table->string('online_admission_payment', 50);
            $table->float('online_admission_amount');
            $table->text('online_admission_instruction');
            $table->text('online_admission_conditions');
            $table->string('online_admission_application_form', 255)->nullable();
            $table->integer('exam_result');
            $table->integer('is_blood_group')->default(1);
            $table->integer('is_student_house')->default(1);
            $table->integer('roll_no')->default(1);
            $table->integer('category');
            $table->integer('religion')->default(1);
            $table->integer('cast')->default(1);
            $table->integer('mobile_no')->default(1);
            $table->integer('student_email')->default(1);
            $table->integer('admission_date')->default(1);
            $table->integer('lastname');
            $table->integer('middlename')->default(1);
            $table->integer('student_photo')->default(1);
            $table->integer('student_height')->default(1);
            $table->integer('student_weight')->default(1);
            $table->integer('measurement_date')->default(1);
            $table->integer('father_name')->default(1);
            $table->integer('father_phone')->default(1);
            $table->integer('father_occupation')->default(1);
            $table->integer('father_pic')->default(1);
            $table->integer('mother_name')->default(1);
            $table->integer('mother_phone')->default(1);
            $table->integer('mother_occupation')->default(1);
            $table->integer('mother_pic')->default(1);
            $table->integer('guardian_name');
            $table->integer('guardian_relation')->default(1);
            $table->integer('guardian_phone');
            $table->integer('guardian_email')->default(1);
            $table->integer('guardian_pic')->default(1);
            $table->integer('guardian_occupation');
            $table->integer('guardian_address')->default(1);
            $table->integer('current_address')->default(1);
            $table->integer('permanent_address')->default(1);
            $table->integer('route_list')->default(1);
            $table->integer('hostel_id')->default(1);
            $table->integer('bank_account_no')->default(1);
            $table->integer('ifsc_code');
            $table->integer('bank_name');
            $table->integer('national_identification_no')->default(1);
            $table->integer('local_identification_no')->default(1);
            $table->integer('rte')->default(1);
            $table->integer('previous_school_details')->default(1);
            $table->integer('student_note')->default(1);
            $table->integer('upload_documents')->default(1);
            $table->integer('student_barcode')->default(1);
            $table->integer('staff_designation')->default(1);
            $table->integer('staff_department')->default(1);
            $table->integer('staff_last_name')->default(1);
            $table->integer('staff_father_name')->default(1);
            $table->integer('staff_mother_name')->default(1);
            $table->integer('staff_date_of_joining')->default(1);
            $table->integer('staff_phone')->default(1);
            $table->integer('staff_emergency_contact')->default(1);
            $table->integer('staff_marital_status')->default(1);
            $table->integer('staff_photo')->default(1);
            $table->integer('staff_current_address')->default(1);
            $table->integer('staff_permanent_address')->default(1);
            $table->integer('staff_qualification')->default(1);
            $table->integer('staff_work_experience')->default(1);
            $table->integer('staff_note')->default(1);
            $table->integer('staff_epf_no')->default(1);
            $table->integer('staff_basic_salary')->default(1);
            $table->integer('staff_contract_type')->default(1);
            $table->integer('staff_work_shift')->default(1);
            $table->integer('staff_work_location')->default(1);
            $table->integer('staff_leaves')->default(1);
            $table->integer('staff_account_details')->default(1);
            $table->integer('staff_social_media')->default(1);
            $table->integer('staff_upload_documents')->default(1);
            $table->integer('staff_barcode')->default(1);
            $table->string('staff_notification_email', 50);
            $table->text('mobile_api_url');
            $table->string('app_primary_color_code', 20)->nullable();
            $table->string('app_secondary_color_code', 20)->nullable();
            $table->text('admin_mobile_api_url');
            $table->string('admin_app_primary_color_code', 20);
            $table->string('admin_app_secondary_color_code', 20);
            $table->string('app_logo', 250)->nullable();
            $table->integer('student_profile_edit')->default(0);
            $table->string('start_week', 10);
            $table->integer('my_question');
            $table->string('superadmin_restriction', 20);
            $table->string('student_timeline', 20);
            $table->integer('calendar_event_reminder')->nullable();
            $table->string('event_reminder', 20);
            $table->string('student_login', 100)->nullable();
            $table->string('parent_login', 100)->nullable();
            $table->integer('student_panel_login')->default(1);
            $table->integer('parent_panel_login')->default(1);
            $table->integer('is_student_feature_lock')->default(0);
            $table->integer('maintenance_mode')->default(0);
            $table->integer('lock_grace_period')->default(0);
            $table->integer('is_offline_fee_payment')->default(0);
            $table->text('offline_bank_payment_instruction');
            $table->string('scan_code_type', 50)->default('barcode');
            $table->timestamp('created_at')->useCurrent();
            $table->date('updated_at')->nullable();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('sch_settings');
    }
};
